#!/usr/bin/env python3
"""Build the single-file curl entry from the canonical remediation modules."""

import argparse
import base64
import hashlib
import io
from pathlib import Path
import textwrap
import zipfile

ROOT = Path(__file__).resolve().parents[1]
MODULES = (
    'tools/fix_games_backdoor.py',
    'tools/repair_system.py',
    'tools/repair_recovery.py',
    'tools/ssh_policy.py',
    'tools/key_input.py',
)

TEMPLATE = r'''#!/usr/bin/env bash
# Generated by tools/build_standalone.py; edit the Python sources, not this file.
# Review the source and use a trusted, pinned HTTPS URL before running as root.
set -euo pipefail

run_bundle() {
    export PATH=/usr/sbin:/usr/bin:/sbin:/bin
    umask 077
    if ! command -v python3 >/dev/null 2>&1; then
        printf '%s\n' '需要预先安装 Python 3.9+；启动脚本不会自动安装软件。' >&2
        return 69
    fi
    NEED_TTY=1
    for argument in "$@"; do
        case "$argument" in --help|-h|--check) NEED_TTY=0 ;; esac
    done
    if (( NEED_TTY )); then
        if ! { exec 3<>/dev/tty; } 2>/dev/null; then
            printf '%s\n' '需要交互终端；请先使用 ssh -t 登录目标服务器再运行。' >&2
            return 2
        fi
    fi
    WORKDIR=$(mktemp -d /tmp/games-repair-run.XXXXXXXX)
    trap 'rm -rf -- "$WORKDIR"' EXIT
    trap 'exit 130' INT
    trap 'exit 143' TERM
    trap 'exit 129' HUP
    python3 -I - "$WORKDIR" <<'GAMES_REPAIR_ARCHIVE'
import base64
import hashlib
import io
from pathlib import Path
import sys
import zipfile

if sys.version_info < (3, 9):
    print('需要 Python 3.9 或更新版本。', file=sys.stderr)
    raise SystemExit(69)
encoded = """
@ARCHIVE@
"""
try:
    payload = base64.b64decode(''.join(encoded.split()), validate=True)
    if hashlib.sha256(payload).hexdigest() != '@SHA256@':
        raise ValueError('Archive checksum mismatch')
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        expected = @MODULES@
        if sorted(archive.namelist()) != sorted(expected):
            raise ValueError('Unexpected archive members')
        root = Path(sys.argv[1])
        (root / 'tools').mkdir(mode=0o700)
        for name in expected:
            with (root / name).open('xb') as output:
                output.write(archive.read(name))
except (ValueError, OSError, zipfile.BadZipFile, RuntimeError) as error:
    print('下载内容损坏或解包失败，未执行修复：' + str(error), file=sys.stderr)
    raise SystemExit(65)
GAMES_REPAIR_ARCHIVE
    if (( NEED_TTY )); then
        python3 -I "$WORKDIR/tools/fix_games_backdoor.py" "$@" <&3 2>&3
    else
        python3 -I "$WORKDIR/tools/fix_games_backdoor.py" "$@"
    fi
}

# Define the entire function before invoking it: a truncated download cannot
# begin remediation while the rest of the payload is still arriving.
run_bundle "$@"
'''


def build_script():
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w') as archive:
        for name in MODULES:
            source = (ROOT / name).read_bytes()
            compile(source, name, 'exec')
            info = zipfile.ZipInfo(name)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100600 << 16
            archive.writestr(info, source)
    payload = buffer.getvalue()
    encoded = '\n'.join(textwrap.wrap(base64.b64encode(payload).decode(), width=100))
    return (TEMPLATE.replace('@ARCHIVE@', encoded)
            .replace('@SHA256@', hashlib.sha256(payload).hexdigest())
            .replace('@MODULES@', repr(MODULES)))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'fix-games.sh')
    args = parser.parse_args()
    args.output.write_text(build_script())
    args.output.chmod(0o755)
    print(args.output)


if __name__ == '__main__':
    main()
